import type { Metadata } from "next";
import "./globals.css";

const siteUrl = "https://newlupin.com";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "Lupin — Protect Your Dignity",
    template: "%s | Lupin",
  },
  description:
    "Lupin is a public support platform where people can share difficult workplace, school, HR, legal, retaliation, discrimination, and unfair treatment stories, receive public support, and protect their dignity.",
  applicationName: "Lupin",
  authors: [{ name: "Lupin" }],
  creator: "Lupin",
  publisher: "Lupin",
  keywords: [
    "Lupin",
    "newlupin",
    "newlupin.com",
    "protect your dignity",
    "public support platform",
    "workplace unfairness",
    "school unfairness",
    "institutional unfairness",
    "HR complaint",
    "HR retaliation",
    "workplace retaliation",
    "school retaliation",
    "academic retaliation",
    "institutional retaliation",
    "legal retaliation",
    "employer retaliation",
    "manager retaliation",
    "supervisor retaliation",
    "retaliation story",
    "retaliation evidence",
    "retaliation support",
    "unfair treatment",
    "unfair dismissal",
    "wrongful termination",
    "hostile workplace",
    "hostile work environment",
    "toxic workplace",
    "toxic boss",
    "abusive boss",
    "abusive workplace",
    "power harassment",
    "workplace bullying",
    "academic bullying",
    "school bullying",
    "professional bullying",
    "institutional bullying",
    "HR abuse",
    "HR injustice",
    "HR misconduct",
    "human resources complaint",
    "employee complaint",
    "employee rights",
    "worker rights",
    "student rights",
    "disability rights",
    "disability discrimination",
    "disability retaliation",
    "reasonable accommodation",
    "accommodation denial",
    "ADA retaliation",
    "ADA discrimination",
    "civil rights",
    "civil rights complaint",
    "legal support",
    "public legal support",
    "public accountability",
    "public testimony",
    "anonymous testimony",
    "anonymous stories",
    "anonymous reporting",
    "whistleblowing support",
    "whistleblower support",
    "truthful reporting",
    "evidence based reporting",
    "documented misconduct",
    "documented unfairness",
    "workplace story",
    "school story",
    "legal story",
    "HR story",
    "career damage",
    "professional retaliation",
    "career retaliation",
    "performance review retaliation",
    "false accusation",
    "one sided investigation",
    "biased investigation",
    "unfair investigation",
    "internal investigation",
    "institutional cover up",
    "institutional accountability",
    "management abuse",
    "supervisor abuse",
    "manager abuse",
    "power imbalance",
    "workplace dignity",
    "student dignity",
    "professional dignity",
    "public dignity",
    "support lawsuit",
    "lawsuit support",
    "legal complaint",
    "civil complaint",
    "employment dispute",
    "academic dispute",
    "institutional dispute",
    "workplace grievance",
    "school grievance",
    "HR grievance",
    "grievance support",
    "public complaint platform",
    "support victims",
    "support survivors",
    "survivor story",
    "victim support",
    "public support",
    "social support",
    "online support",
    "community support",
    "share your story",
    "tell your story",
    "truth and dignity",
    "justice support",
    "accountability platform",
    "evidence archive",
    "incident documentation",
    "timeline documentation",
    "workplace incident",
    "school incident",
    "legal incident",
    "Shirley Ryan AbilityLab",
    "SRALab",
    "rehabilitation research workplace",
    "Chicago workplace retaliation",
    "Chicago HR complaint",
    "Chicago legal support",
    "Illinois workplace retaliation",
    "Illinois employment dispute"
  ],
  alternates: {
    canonical: siteUrl,
  },
  openGraph: {
    title: "Lupin — Protect Your Dignity",
    description:
      "Share difficult workplace, school, HR, legal, retaliation, discrimination, and unfair treatment stories. Receive public support and protect your dignity.",
    url: siteUrl,
    siteName: "Lupin",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Lupin — Protect Your Dignity",
    description:
      "Share difficult workplace, school, HR, legal, retaliation, discrimination, and unfair treatment stories. Receive public support and protect your dignity.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
 
